version: "3"
services:
    node:
#      build: ./build/node
      image: node
      volumes:
        - ./:/app
        - /root/php-docker/:/data
      environment:
#          - NODE_ENV=production
          - PORT=3000
      working_dir: /app
      command:
        - /bin/bash
        - -c 
        - bash start.bash
      expose: 
        - "3000"
      restart: on-failure
      logging:
        options:
          max-size: 500k
#      networks:
#        - backend
      ports:
          - 3000:1437
#networks:
#  zotabox:
#    external: true
#  backend:
#    driver: bridge